### ISSUE TITLE
Autocomplete with a root path doesn't seem possible

### ISSUE THREAD

**Issue by tobilg** [vorpaljs/vorpal-autocomplete-fs#1]
I tried to use `vorpal-autocomplete-fs` (on Mac OS X / Node 4 LTS) like the following:

``` javascript
vorpal
    .command('config load [pathToConfig]', 'Loads an existing configuration')
    .autocomplete(fsAutocomplete())
    .action(function(args, callback) {
        ...
    });
```

Now, when I double tap TAB, the behaviour is the following:

```
ctl $ config load /
config/  .DS_Store  .gitignore    index.js  lib/  modules/  node_modules/  package.json  README.md
```

It doesn't start from the root directory, but in the project root. Is this the normal behavior? 

I saw that when I prepend double slashed and then press TAB twice, it show me the content of my `/` folder. I think the according lines for this behavior are https://github.com/vorpaljs/vorpal-autocomplete-fs/blob/master/dist/index.js#L188-L191

**Comment by tobilg** [comment]
Any updates?

**Comment by tobilg** [comment]
Closing due to no reaction

**Comment by arealmaas** [comment]
@tobilg Did you fork and fix the issue?

**Comment by tobilg** [comment]
@AlmaasAre No, I just removed it, as I didn't really find the bug...
